// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RateController from "./rate_controller"
application.register("rate", RateController)

import TomSelect from 'tom-select'

let selects = []

document.addEventListener("turbo:before-cache", function() {
  selects.forEach((select) => {
    select.destroy()
  })
})

document.addEventListener("turbo:load", function() {
  document.querySelectorAll('.js-multiple-select').forEach((element) => {
    new TomSelect(element)
  })
})
